'use client';
import { useEffect, useState } from 'react';
import { Shell } from '@/components/shell';
import { api, uploadFile } from '@/lib/api';

const empty:any={code:'',nameAr:'',nameEn:'',minLevel:1,maxLevel:'',imageUrl:'',colorHex:'#CD7F32',rewards:{},enabled:true,sortOrder:0};
export default function StagesPage(){
  const[items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[editing,setEditing]=useState<string|null>(null);const[rewardText,setRewardText]=useState('{}');const[error,setError]=useState('');
  const load=()=>api<any[]>('/admin/stages').then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
  const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
  async function upload(file?:File){if(!file)return;try{const r=await uploadFile('/admin/uploads/assets',file);set('imageUrl',r.url)}catch(e:any){setError(e.message)}}
  async function save(e:React.FormEvent){e.preventDefault();setError('');try{const body={...form,minLevel:Number(form.minLevel),maxLevel:form.maxLevel===''?null:Number(form.maxLevel),sortOrder:Number(form.sortOrder),rewards:JSON.parse(rewardText||'{}')};await api(editing?`/admin/stages/${editing}`:'/admin/stages',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setForm(empty);setRewardText('{}');setEditing(null);await load()}catch(e:any){setError(e.message)}}
  function edit(x:any){setEditing(x.id);setForm({...x,maxLevel:x.maxLevel??''});setRewardText(JSON.stringify(x.rewards||{},null,2));window.scrollTo({top:0,behavior:'smooth'})}
  return <Shell><h1>Stages & ranks</h1><p className="muted">Group levels into visible stages such as Bronze, Silver, Gold and Champion.</p>{error&&<p className="error">{error}</p>}
  <form className="card form-grid" onSubmit={save}><label>Code<input className="input" value={form.code} disabled={editing!==null} onChange={e=>set('code',e.target.value.toUpperCase())} required/></label><label>Arabic name<input className="input" value={form.nameAr} onChange={e=>set('nameAr',e.target.value)} required/></label><label>English name<input className="input" value={form.nameEn} onChange={e=>set('nameEn',e.target.value)} required/></label><label>Minimum level<input className="input" type="number" min="1" value={form.minLevel} onChange={e=>set('minLevel',e.target.value)}/></label><label>Maximum level<input className="input" type="number" min="1" value={form.maxLevel} onChange={e=>set('maxLevel',e.target.value)} placeholder="Leave empty for no maximum"/></label><label>Color<input className="input" type="color" value={form.colorHex||'#CD7F32'} onChange={e=>set('colorHex',e.target.value)}/></label><label>Stage image<input className="input" value={form.imageUrl||''} onChange={e=>set('imageUrl',e.target.value)}/><input className="input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><label>Sort order<input className="input" type="number" value={form.sortOrder} onChange={e=>set('sortOrder',e.target.value)}/></label><label className="check"><input type="checkbox" checked={!!form.enabled} onChange={e=>set('enabled',e.target.checked)}/> Enabled</label><label className="full">Rewards JSON<textarea className="input textarea" value={rewardText} onChange={e=>setRewardText(e.target.value)}/></label><div className="row full"><button className="btn">{editing?'Save stage':'Add stage'}</button>{editing&&<button className="btn secondary" type="button" onClick={()=>{setEditing(null);setForm(empty);setRewardText('{}')}}>Cancel</button>}</div></form>
  <div className="grid">{items.map(x=><div className="card" key={x.id}><div className="row"><div className="stage-dot" style={{background:x.colorHex||'#777'}}/><h2>{x.nameEn}</h2><span className="badge">{x.enabled?'ACTIVE':'DISABLED'}</span></div><p>{x.nameAr}</p><p className="muted">Levels {x.minLevel}–{x.maxLevel??'∞'} · {x.code}</p><code>{JSON.stringify(x.rewards||{})}</code><div className="row"><button className="btn secondary" onClick={()=>edit(x)}>Edit</button><button className="btn danger" onClick={async()=>{if(confirm('Disable this stage?')){await api(`/admin/stages/${x.id}`,{method:'DELETE'});load()}}}>Disable</button></div></div>)}</div></Shell>
}
