import 'package:flutter/material.dart';
import 'app_controller.dart';

extension AppTranslation on BuildContext {
  String tr(String text) {
    final controller = AppScope.of(this);
    if (!controller.isArabic) return text;
    final exact = _ar[text];
    if (exact != null) return exact;
    var result = text;
    for (final entry in _arReplacements.entries) {
      result = result.replaceAll(entry.key, entry.value);
    }
    return result;
  }
}

const Map<String, String> _ar = {
  'Ludo Champion': 'MAURITANIA LUDO',
  'MAURITANIA LUDO': 'MAURITANIA LUDO',
  'LUDO': 'لودو',

  'Play real server Ludo': 'العب لودو حقيقية عبر الخادم',
  'Create 2-player and 4-player matches with dice, moves and rules validated by the server.': 'أنشئ مباريات للاعبين أو أربعة لاعبين مع نرد وحركات وقواعد يتحقق منها الخادم.',
  'Customize your game': 'خصص شكل لعبتك',
  'Buy and equip real boards, dice and frames from the connected store and inventory.': 'اشترِ وجهز رقعاً ونرداً وإطارات حقيقية من المتجر والحقيبة المتصلين.',
  'Progress and wallet': 'التقدم والمحفظة',
  'Earn XP, move through levels and stages, and track real wallet and transaction records.': 'اكسب نقاط الخبرة وتقدم عبر المستويات والمراحل وتابع المحفظة وسجل المعاملات الحقيقي.',
  'Home': 'الرئيسية', 'Store': 'المتجر', 'Rooms': 'الغرف', 'Wallet': 'المحفظة', 'Profile': 'الملف الشخصي',
  'Choose Language': 'اختر اللغة', 'Choose your language': 'اختر لغتك', 'English': 'الإنجليزية', 'Arabic': 'العربية',
  'Login': 'تسجيل الدخول', 'Log in': 'تسجيل الدخول', 'Register': 'إنشاء حساب', 'Create account': 'إنشاء حساب',
  'Forgot password?': 'نسيت كلمة المرور؟', 'Reset password': 'إعادة تعيين كلمة المرور', 'Continue': 'متابعة', 'Cancel': 'إلغاء',
  'Confirm': 'تأكيد', 'Apply': 'تطبيق', 'Save changes': 'حفظ التعديلات', 'Back to Home': 'العودة إلى الرئيسية',
  'Change photo': 'تغيير الصورة', 'Change profile photo': 'تغيير صورة الملف الشخصي',
  'Take a photo': 'التقاط صورة', 'Open the camera': 'فتح كاميرا الهاتف', 'Choose from gallery': 'اختيار من المعرض',
  'Select an existing photo': 'اختر صورة موجودة', 'Remove current photo': 'حذف الصورة الحالية', 'Use the default avatar': 'استخدام الصورة الافتراضية',
  'Edit Profile': 'تعديل الملف الشخصي', 'Edit profile': 'تعديل الملف الشخصي', 'Statistics': 'الإحصائيات',
  'Match history': 'سجل المباريات', 'Inventory': 'الحقيبة', 'Achievements': 'الإنجازات', 'Invite friends': 'دعوة الأصدقاء',
  'Account settings': 'إعدادات الحساب', 'Log out': 'تسجيل الخروج', 'Log out?': 'هل تريد تسجيل الخروج؟',
  'Matches': 'المباريات', 'Wins': 'الانتصارات', 'Win rate': 'نسبة الفوز', 'History': 'السجل',
  'Choose Game Mode': 'اختر نمط اللعب', 'Wager Match': 'مباراة رهان', 'Casual Match': 'مباراة عادية', 'Private Room': 'غرفة خاصة',
  'Friends Match': 'مباراة أصدقاء', 'Tournaments': 'البطولات', 'Practice with Bots': 'تدريب ضد الكمبيوتر',
  'Classic': 'كلاسيكي', 'Quick': 'سريع', 'Master': 'احترافي', 'Rules': 'القواعد', 'Confirm Match': 'تأكيد المباراة',
  '2 Players': 'لاعبان', '4 Players': 'أربعة لاعبين', 'Customize your match': 'خصص مباراتك',
  'Finding players...': 'جاري البحث عن لاعبين...', 'Cancel Search': 'إلغاء البحث', 'Opponent found': 'تم العثور على خصم',
  'OPPONENT FOUND': 'تم العثور على خصم', 'Estimated wait: under 20 seconds': 'الوقت المتوقع: أقل من 20 ثانية',
  'Current Match Rules': 'قوانين المباراة الحالية', 'Leave match?': 'مغادرة المباراة؟', 'Continue playing': 'متابعة اللعب', 'Forfeit': 'انسحاب',
  'Chat': 'الدردشة', 'Gifts': 'الهدايا', 'Skills': 'المهارات', 'Sound': 'الصوت', 'Watch': 'المشاهدون',
  'Quick Chat': 'الرسائل السريعة', 'Quick Text': 'نصوص سريعة', 'Emojis': 'الرموز التعبيرية', 'Send Gift': 'إرسال هدية',
  'Roll the dice': 'ارمِ النرد', 'Select a token': 'اختر قطعة', 'Your turn': 'دورك', 'seconds remaining': 'ثوانٍ متبقية',
  'No legal move': 'لا توجد حركة قانونية', 'Three consecutive sixes: turn cancelled': 'ثلاث رميات 6 متتالية: أُلغي الدور',
  'Token reached home': 'وصلت القطعة إلى المنزل', 'Captured opponent piece! Extra roll': 'تم أسر قطعة الخصم! رمية إضافية',
  'Green': 'الأخضر', 'Yellow': 'الأصفر', 'Red': 'الأحمر', 'Blue': 'الأزرق',
  'Green Player': 'اللاعب الأخضر', 'Yellow Player': 'اللاعب الأصفر', 'Red Player': 'اللاعب الأحمر', 'Blue Player': 'اللاعب الأزرق',
  'Profile saved locally': 'تم حفظ الملف الشخصي على الجهاز', 'Language': 'اللغة', 'Full settings': 'الإعدادات الكاملة',
  'Deposit': 'إيداع', 'Withdraw': 'سحب', 'Transactions': 'المعاملات', 'Notifications': 'الإشعارات',
  'Total Balance': 'الرصيد الإجمالي', 'Available to withdraw': 'المتاح للسحب', 'Available wallet balance': 'رصيد المحفظة المتاح',
  'Insufficient wallet balance': 'الرصيد غير كافٍ', 'Purchase successful': 'تم الشراء بنجاح', 'Price': 'السعر',
  'Good luck!': 'حظاً موفقاً!', 'Nice move!': 'حركة جميلة!', 'Well played!': 'لعب رائع!', 'Hurry up!': 'أسرع من فضلك!',
  'Great roll!': 'رمية رائعة!', 'Rematch?': 'إعادة المباراة؟', 'Play fast please': 'العب بسرعة من فضلك',
  'Create room': 'إنشاء غرفة', 'Private room': 'غرفة خاصة', 'Paste room code': 'الصق رمز الغرفة', 'ROOM CODE': 'رمز الغرفة',
  'Copy code': 'نسخ الرمز', 'Copy invite code': 'نسخ رمز الدعوة', 'I am ready': 'أنا جاهز',
  'The host can start when all players are ready.': 'يمكن للمضيف البدء عندما يصبح جميع اللاعبين جاهزين.',
  'Match begins automatically': 'تبدأ المباراة تلقائياً', 'Allow spectators': 'السماح للمشاهدين',
  'Users can watch but cannot affect the match.': 'يمكن للمستخدمين المشاهدة دون التأثير على المباراة.',
  'Remember me': 'تذكرني', 'Resend code': 'إعادة إرسال الرمز',
  'Terms, privacy and wagering policy': 'الشروط والخصوصية وسياسة الرهانات',
  'I accept the match rules and forfeit policy': 'أوافق على قوانين المباراة وسياسة الانسحاب',
  'I confirm that I meet the required age and accept the terms, privacy policy and game rules.': 'أؤكد أنني أبلغ السن المطلوب وأوافق على الشروط وسياسة الخصوصية وقواعد اللعبة.',
  'Mark all read': 'تحديد الكل كمقروء', 'View all': 'عرض الكل', 'Skip': 'تخطي',
  'Music': 'الموسيقى', 'Sound effects': 'المؤثرات الصوتية', 'Vibration': 'الاهتزاز',
  'Background music': 'موسيقى الخلفية', 'Effects volume': 'مستوى المؤثرات', 'Music volume': 'مستوى الموسيقى',
  'Play music in menus and rooms.': 'تشغيل الموسيقى في القوائم والغرف.', 'Haptic feedback for actions and alerts.': 'اهتزاز عند الإجراءات والتنبيهات.',
  'Show online status': 'إظهار حالة الاتصال', 'Allow direct messages': 'السماح بالرسائل المباشرة',
  'Allow friend invitations': 'السماح بدعوات الأصدقاء', 'Allow friends to see when you are online.': 'السماح للأصدقاء برؤية حالة اتصالك.',
  'Friends can send private messages.': 'يمكن للأصدقاء إرسال رسائل خاصة.', 'Receive game and room invitations.': 'استقبال دعوات اللعب والغرف.',
  'Speaker seats': 'مقاعد المتحدثين', 'Room chat': 'دردشة الغرفة', 'Hand raised': 'تم رفع اليد',
  'Creation fee': 'رسوم الإنشاء', 'Account number copied': 'تم نسخ رقم الحساب', 'Copy account number': 'نسخ رقم الحساب',
  'ADMIN ACCOUNT': 'حساب الإدارة', 'Minimum 300 MRU • Maximum 100,000 MRU': 'الحد الأدنى 300 MRU • الحد الأقصى 100,000 MRU',
  'Enter an amount between 300 and 100,000 MRU': 'أدخل مبلغاً بين 300 و100,000 MRU',
  'The amount cannot be withdrawn from the current balance.': 'لا يمكن سحب المبلغ من الرصيد الحالي.',
  'Confirm tournament entry': 'تأكيد الاشتراك في البطولة', 'Tournament joined': 'تم الانضمام إلى البطولة',
  'Grand Championship': 'بطولة الأبطال الكبرى', 'GRAND CHAMPIONSHIP': 'بطولة الأبطال الكبرى',
  'Registration closes in 2d 08h': 'يغلق التسجيل خلال يومين و8 ساعات', 'Starts in 01:42:15': 'تبدأ خلال 01:42:15',
  'WEEKEND BONUS': 'مكافأة نهاية الأسبوع', 'PLAY & WIN': 'العب واربح', 'Get up to 30% extra coins': 'احصل على عملات إضافية حتى 30%',
  'Offer ends in 08:42:17': 'ينتهي العرض خلال 08:42:17', 'Welcome back,': 'مرحباً بعودتك،',
  'Open frontend screen catalog': 'فتح فهرس واجهات التطبيق', 'Fair-play guarantees': 'ضمانات اللعب العادل',
  'Dice, movement, gifts and buttons.': 'النرد والحركة والهدايا والأزرار.',
  'Skills are available only in Casual Skills mode. They are disabled in wager matches and official tournaments.': 'المهارات متاحة فقط في النمط الترفيهي، وهي معطلة في مباريات الرهان والبطولات الرسمية.',
  'Select your active dice, frame and board before playing.': 'اختر النرد والإطار واللوحة النشطة قبل اللعب.',
  'JPG or PNG, maximum 10 MB': 'JPG أو PNG، بحد أقصى 10 ميغابايت',
  'Account number': 'رقم الحساب', 'Full name': 'الاسم الكامل', 'Phone number': 'رقم الهاتف',
  'Level': 'المستوى',
  'Next level': 'المستوى التالي',
  'Maximum configured level': 'أعلى مستوى مهيأ',
  'Inventory is empty': 'الحقيبة فارغة',
  'Purchased and rewarded boards, dice, frames and other items will appear here.': 'ستظهر هنا الرقع والنرد والإطارات والعناصر التي تشتريها أو تحصل عليها كمكافآت.',
  'This build uses real authentication, profile, wallet, payments, store, inventory, appearance, levels, stages, transactions and authoritative match APIs. Tournaments, voice rooms, referrals, achievements and support are the remaining disabled modules.': 'تستخدم هذه النسخة تسجيل الدخول والملف الشخصي والمحفظة والدفع والمتجر والحقيبة والمظهر والمستويات والمراحل والمعاملات ومحرك المباريات الحقيقي عبر الخادم. الوحدات المتبقية المعطلة هي البطولات والغرف الصوتية والدعوات والإنجازات والدعم.',
  'Cash balance': 'الرصيد النقدي',
  'Locked balance': 'الرصيد المحجوز',
  'Coins': 'العملات',
  'Gems': 'الجواهر',
  'Connected test environment': 'بيئة اختبار متصلة',
  'The information on this page comes from the backend. Pull down to refresh it.': 'المعلومات في هذه الصفحة تأتي من الخادم. اسحب للأسفل لتحديثها.',
  'Start a real match': 'ابدأ مباراة حقيقية',
  'Casual matches use the server without reserving wallet funds. Wager matches require an approved cash balance.': 'المباريات العادية تعمل عبر الخادم دون حجز رصيد. مباريات الرهان تتطلب رصيداً نقدياً معتمداً.',
  'Head-to-head server match': 'مباراة مباشرة بين لاعبين عبر الخادم',
  'Full server match': 'مباراة كاملة عبر الخادم',
  'Recent match': 'آخر مباراة',
  'No matches yet': 'لا توجد مباريات بعد',
  'Create a casual match from another test account to begin testing the real game flow.': 'أنشئ مباراة عادية من حساب اختبار آخر لبدء تجربة مسار اللعب الحقيقي.',
  'Match': 'المباراة',
  'No notifications': 'لا توجد إشعارات',
  'Wallet and match notifications from the server will appear here.': 'ستظهر هنا إشعارات المحفظة والمباريات القادمة من الخادم.',
  'Notification': 'إشعار',
  'Developer tools': 'أدوات المطور',
  'Catalog disabled': 'تم تعطيل فهرس الواجهات',
  'The production test build no longer exposes screens backed by mock data.': 'نسخة الاختبار لم تعد تعرض شاشات تعتمد على بيانات وهمية.',
  'Bonus balance': 'رصيد المكافآت',
  'Recent transactions': 'أحدث المعاملات',
  'No transactions': 'لا توجد معاملات',
  'Approved deposits, withdrawals, match prizes and wallet reservations will appear here.': 'ستظهر هنا الإيداعات والسحوبات المعتمدة وجوائز المباريات وحجوزات الرصيد.',
  'Create a deposit request': 'إنشاء طلب إيداع',
  'The balance changes only after an administrator verifies and approves the transfer.': 'لن يتغير الرصيد إلا بعد أن يراجع المدير التحويل ويوافق عليه.',
  'Amount': 'المبلغ',
  'Enter amount in MRU': 'أدخل المبلغ بعملة MRU',
  'Payment method': 'طريقة الدفع',
  'Bankily': 'بنكيلي',
  'Mobile wallet transfer': 'تحويل عبر المحفظة المحمولة',
  'Sedad': 'سداد',
  'Sedad transfer': 'تحويل عبر سداد',
  'Other': 'أخرى',
  'Another method configured by the administration': 'طريقة أخرى تحددها الإدارة',
  'Enter a valid amount': 'أدخل مبلغاً صالحاً',
  'Transfer details': 'تفاصيل التحويل',
  'Transfer the exact amount': 'حوّل المبلغ المحدد تماماً',
  'Then upload the receipt and transfer reference for administrative review.': 'ثم ارفع الإيصال ورقم مرجع التحويل لمراجعة الإدارة.',
  'Administration account': 'حساب الإدارة',
  'Not configured by administration': 'لم تحدده الإدارة بعد',
  'Do not consider the deposit completed until its status becomes COMPLETED in the transaction list.': 'لا تعتبر الإيداع مكتملاً حتى تصبح حالته مكتمل في قائمة المعاملات.',
  'Upload receipt': 'رفع الإيصال',
  'Submit transfer proof': 'إرسال إثبات التحويل',
  'This creates a pending transaction. The administration must approve it before your balance changes.': 'هذا ينشئ معاملة قيد المراجعة، ويجب أن توافق عليها الإدارة قبل تغير الرصيد.',
  'Choose receipt image': 'اختر صورة الإيصال',
  'Transfer reference': 'مرجع التحويل',
  'Optional transaction number': 'رقم العملية اختياري',
  'Submit deposit request': 'إرسال طلب الإيداع',
  'Select the transfer receipt': 'اختر إيصال التحويل',
  'Receipt upload failed': 'فشل رفع الإيصال',
  'Deposit request failed': 'فشل إرسال طلب الإيداع',
  'Request submitted': 'تم إرسال الطلب',
  'Deposit is pending review': 'الإيداع قيد المراجعة',
  'Track the request in Transactions. The cash balance will change only after approval.': 'تابع الطلب من المعاملات. سيتغير الرصيد النقدي بعد الموافقة فقط.',
  'Open transactions': 'فتح المعاملات',
  'Complete the recipient information': 'أكمل معلومات المستلم',
  'Review withdrawal': 'مراجعة السحب',
  'Confirm withdrawal request': 'تأكيد طلب السحب',
  'The amount will move from cash to locked balance while the request is pending.': 'سينتقل المبلغ من الرصيد النقدي إلى الرصيد المحجوز أثناء مراجعة الطلب.',
  'Submit withdrawal request': 'إرسال طلب السحب',
  'Withdrawal request failed': 'فشل إرسال طلب السحب',
  'Withdrawal is pending review': 'السحب قيد المراجعة',
  'The requested amount is now locked. Approval completes the withdrawal; rejection returns it to cash balance.': 'المبلغ المطلوب محجوز الآن. الموافقة تكمل السحب والرفض يعيده إلى الرصيد النقدي.',
  'Transaction details': 'تفاصيل المعاملة',
  'Transaction ID': 'رقم المعاملة',
  'Type': 'النوع',
  'Fee': 'الرسوم',
  'Fees': 'الرسوم',
  'Net amount': 'صافي المبلغ',
  'Description': 'الوصف',
  'Method': 'الطريقة',
  'DEPOSIT': 'إيداع',
  'WITHDRAWAL': 'سحب',
  'ADMIN_ADJUSTMENT': 'تعديل إداري',
  'WAGER_LOCK': 'حجز رهان',
  'WAGER_RELEASE': 'تسوية رهان',
  'MATCH_PRIZE': 'جائزة مباراة',
  'PLATFORM_FEE': 'عمولة المنصة',
  'REFUND': 'استرجاع',
  'STORE_PURCHASE': 'شراء من المتجر',
  'REWARD': 'مكافأة',
  'PENDING': 'قيد المراجعة',
  'PROCESSING': 'قيد المعالجة',
  'COMPLETED': 'مكتمل',
  'REJECTED': 'مرفوض',
  'CANCELLED': 'ملغى',
  'REFUNDED': 'مسترجع',
  'Store is not connected yet': 'المتجر غير متصل بعد',
  'Mock products were removed. Real products, prices, ownership and purchases will appear after the store backend module is enabled.': 'تم حذف المنتجات الوهمية. ستظهر المنتجات والأسعار والمشتريات الحقيقية بعد تفعيل باكند المتجر.',
  'No purchase was created': 'لم تتم أي عملية شراء',
  'The test build does not simulate store purchases. This screen will be activated only after a real server transaction exists.': 'نسخة الاختبار لا تحاكي عمليات شراء. ستُفعّل هذه الشاشة بعد وجود معاملة حقيقية من الخادم.',
  'Social rooms are not connected yet': 'الغرف الاجتماعية غير متصلة بعد',
  'Mock rooms and members were removed. Voice rooms will be displayed only after the social backend and live audio provider are connected.': 'تم حذف الغرف والأعضاء الوهميين. ستظهر الغرف الصوتية بعد ربط الباكند الاجتماعي ومزود الصوت المباشر.',
  'Voice room creation is disabled': 'إنشاء الغرفة الصوتية معطل',
  'A room will not be created locally. This feature requires the social backend and audio service.': 'لن تُنشأ غرفة محلياً. هذه الميزة تحتاج باكند اجتماعي وخدمة صوت.',
  'No real room selected': 'لم يتم اختيار غرفة حقيقية',
  'Open this screen later from a room returned by the backend.': 'افتح هذه الشاشة لاحقاً من غرفة يعيدها الخادم.',
  'Tournaments are not connected yet': 'البطولات غير متصلة بعد',
  'Mock brackets, prizes and participants were removed. The module will appear after tournament tables and administration tools are implemented.': 'تم حذف الجداول والجوائز والمشاركين الوهميين. ستظهر الوحدة بعد تنفيذ جداول البطولات وأدوات الإدارة.',
  'Tournament details': 'تفاصيل البطولة',
  'No real tournament selected': 'لم يتم اختيار بطولة حقيقية',
  'Tournament details must come from the backend.': 'يجب أن تأتي تفاصيل البطولة من الخادم.',
  'Tournament bracket': 'جدول البطولة',
  'No real bracket available': 'لا يوجد جدول حقيقي',
  'The bracket will be generated from real tournament matches.': 'سيتم إنشاء الجدول من مباريات البطولة الحقيقية.',
  'Leaderboard': 'لوحة المتصدرين',
  'Leaderboard is not connected yet': 'لوحة المتصدرين غير متصلة بعد',
  'Player rankings will be calculated by the backend, not by static application data.': 'سيحسب الخادم ترتيب اللاعبين بدلاً من البيانات الثابتة.',
  'Real profile statistics returned by the server': 'إحصائيات حقيقية يعيدها الخادم',
  'Matches stored in the backend': 'مباريات محفوظة في الخادم',
  'This module has no real server data yet': 'هذه الوحدة لا تحتوي بيانات حقيقية من الخادم بعد',
  'Language, sound, privacy and account controls': 'اللغة والصوت والخصوصية وإعدادات الحساب',
  'End the current authenticated session': 'إنهاء جلسة تسجيل الدخول الحالية',
  'Profile photo updated': 'تم تحديث صورة الملف الشخصي',
  'Profile photo update failed': 'فشل تحديث صورة الملف الشخصي',
  'This ends the current session on this device.': 'سيؤدي ذلك إلى إنهاء الجلسة الحالية على هذا الجهاز.',
  'Display name': 'اسم العرض',
  'Country code': 'رمز الدولة',
  'Two-letter code': 'رمز من حرفين',
  'Bio': 'النبذة',
  'Country code must contain two letters': 'يجب أن يتكون رمز الدولة من حرفين',
  'Profile update failed': 'فشل تحديث الملف الشخصي',
  'Experience': 'الخبرة',
  'Losses': 'الخسائر',
  'Real matches created or joined by this account will appear here.': 'ستظهر هنا المباريات الحقيقية التي أنشأها هذا الحساب أو انضم إليها.',
  'Inventory is not connected yet': 'الحقيبة غير متصلة بعد',
  'Mock dice, frames and skills were removed. Owned items will appear after the store and inventory backend is added.': 'تم حذف النرد والإطارات والمهارات الوهمية. ستظهر العناصر المملوكة بعد إضافة باكند المتجر والحقيبة.',
  'Achievements are not connected yet': 'الإنجازات غير متصلة بعد',
  'Achievements will be calculated and granted by the backend.': 'سيحسب الخادم الإنجازات ويمنحها.',
  'Referral system is not connected yet': 'نظام الدعوات غير متصل بعد',
  'No local referral codes or rewards are generated in this build.': 'لا يتم إنشاء رموز دعوة أو مكافآت محلية في هذه النسخة.',
  'Switch the whole application between Arabic and English': 'تبديل التطبيق كاملاً بين العربية والإنجليزية',
  'Music, effects and vibration': 'الموسيقى والمؤثرات والاهتزاز',
  'Social privacy options will be sent to the backend later': 'ستُرسل إعدادات الخصوصية الاجتماعية إلى الخادم لاحقاً',
  'Support module status': 'حالة وحدة الدعم',
  'Not synchronized yet': 'غير متزامن بعد',
  'These social settings remain on this screen only until the social profile backend is added.': 'ستبقى هذه الإعدادات على الجهاز فقط حتى إضافة باكند الملف الاجتماعي.',
  'Support tickets are not connected yet': 'تذاكر الدعم غير متصلة بعد',
  'No fake tickets are created. This module will be connected after the core game test succeeds.': 'لن يتم إنشاء تذاكر وهمية. ستُربط هذه الوحدة بعد نجاح اختبار اللعبة الأساسية.',
  'Connected staging build': 'نسخة تجريبية متصلة',
  'This build uses real authentication, profile, wallet, transaction and match APIs. Store, tournaments, voice rooms, referrals and support remain disabled until their backend modules are implemented.': 'تستخدم هذه النسخة واجهات حقيقية لتسجيل الدخول والملف الشخصي والمحفظة والمعاملات والمباريات. يبقى المتجر والبطولات والغرف الصوتية والدعوات والدعم معطلاً حتى تنفيذ باكندها.',
  'Real server match without reserving wallet funds': 'مباراة حقيقية عبر الخادم دون حجز رصيد',
  'The server reserves the selected amount from every player': 'يحجز الخادم المبلغ المحدد من كل لاعب',
  'Create a server room or join with its six-digit code': 'أنشئ غرفة على الخادم أو انضم عبر رمزها المكون من ستة أرقام',
  'Disabled until the bot service uses the same authoritative game engine': 'معطل حتى تستخدم خدمة الروبوتات محرك اللعبة نفسه',
  'Disabled until the tournament backend is connected': 'معطل حتى يتم ربط باكند البطولات',
  'Number of Players': 'عدد اللاعبين',
  'Select match size': 'اختر حجم المباراة',
  'Every player must use a separate authenticated account during the connected test.': 'يجب أن يستخدم كل لاعب حساباً منفصلاً مسجلاً أثناء الاختبار المتصل.',
  'Head-to-head match': 'مباراة مباشرة بين لاعبين',
  'Full four-player match': 'مباراة كاملة لأربعة لاعبين',
  'Match Rules': 'قوانين المباراة',
  'Choose a rule set': 'اختر مجموعة القواعد',
  'The server applies the selected rule set and validates every roll and move.': 'يطبق الخادم القواعد المختارة ويتحقق من كل رمية وحركة.',
  'Four pieces, a six releases a piece, captures return opponents to base, safe cells protect pieces, and an exact roll is required to finish.': 'أربع قطع، والرقم 6 يخرج القطعة، والأسر يعيد الخصم للقاعدة، والخانات الآمنة تحمي القطع، ويلزم رقم دقيق للوصول للنهاية.',
  'Two pieces per player with shorter server timers. The first player to finish both pieces wins.': 'قطعتان لكل لاعب مع مؤقتات أقصر. يفوز أول لاعب ينهي القطعتين.',
  'Four pieces with strict timers, blockades and the three-consecutive-sixes penalty.': 'أربع قطع مع مؤقتات صارمة وحواجز وعقوبة ثلاث رميات 6 متتالية.',
  'CLASSIC': 'كلاسيكي',
  'QUICK': 'سريع',
  'MASTER': 'احترافي',
  'Choose Wager': 'اختيار الرهان',
  'Total pool before fee': 'إجمالي الصندوق قبل العمولة',
  'Review match': 'مراجعة المباراة',
  'Server-side wager reservation': 'حجز الرهان على الخادم',
  'The stake is reserved only when a match is created. The backend settles the result atomically.': 'يُحجز الرهان عند إنشاء المباراة فقط، ويسوي الخادم النتيجة ضمن عملية واحدة آمنة.',
  'Your entry': 'قيمة دخولك',
  'Start matchmaking': 'بدء البحث عن لاعبين',
  'Matchmaking': 'البحث عن لاعبين',
  'Open the application with another account and choose the same mode, player count, rule set and wager.': 'افتح التطبيق بحساب آخر واختر نفس النمط وعدد اللاعبين والقواعد والرهان.',
  'Matchmaking failed': 'فشل البحث عن لاعبين',
  'Create a private server room': 'إنشاء غرفة خاصة على الخادم',
  'Share the generated six-digit code with authenticated players.': 'شارك الرمز المكون من ستة أرقام مع لاعبين مسجلين.',
  '0 for a no-wager room': 'اكتب 0 لغرفة بلا رهان',
  'Join with code': 'الانضمام بالرمز',
  'Room creation failed': 'فشل إنشاء الغرفة',
  'Join Private Room': 'الانضمام إلى غرفة خاصة',
  'Use the six-digit code generated by the host backend.': 'استخدم الرمز المكون من ستة أرقام الذي أنشأه الخادم للمضيف.',
  'Room code': 'رمز الغرفة',
  'Find Room': 'البحث عن الغرفة',
  'Enter the six-digit room code': 'أدخل رمز الغرفة المكون من ستة أرقام',
  'Room not found': 'الغرفة غير موجودة',
  'Room Found': 'تم العثور على الغرفة',
  'Review the actual server room before joining.': 'راجع بيانات الغرفة الحقيقية قبل الانضمام.',
  'Mode': 'النمط',
  'Open waiting room': 'فتح غرفة الانتظار',
  'Join room': 'الانضمام إلى الغرفة',
  'Could not join room': 'تعذر الانضمام إلى الغرفة',
  'Waiting Room': 'غرفة الانتظار',
  'Waiting for players': 'بانتظار اللاعبين',
  'Open the application on another device or emulator with another account and join the same room code.': 'افتح التطبيق على جهاز أو محاكي آخر بحساب مختلف وانضم إلى رمز الغرفة نفسه.',
  'Start Match': 'بدء المباراة',
  'Waiting for host': 'بانتظار المضيف',
  'The host account must start the match.': 'يجب أن يبدأ حساب المضيف المباراة.',
  'Match start failed': 'فشل بدء المباراة',
  'Match result': 'نتيجة المباراة',
  'Match completed': 'انتهت المباراة',
  'The final result, wallet settlement and profile statistics are loaded from the backend after refresh.': 'يتم تحميل النتيجة النهائية وتسوية المحفظة وإحصائيات الملف من الخادم بعد التحديث.',
  'Match details': 'تفاصيل المباراة',
  'Open a real match from history': 'افتح مباراة حقيقية من السجل',
  'The connected game screen includes the current server state and event information.': 'تتضمن شاشة اللعب المتصلة حالة المباراة الحالية ومعلومات الأحداث من الخادم.',
  'Local game removed': 'تم حذف اللعب المحلي',
  'The local random game was removed. Open a match created by the backend.': 'تم حذف اللعبة العشوائية المحلية. افتح مباراة أنشأها الخادم.',
  'No match selected': 'لم يتم اختيار مباراة',
  'Open a real match from matchmaking, a private room or match history.': 'افتح مباراة حقيقية من البحث أو غرفة خاصة أو سجل المباريات.',
  'Forfeiting is recorded by the backend and may settle the wager as a loss.': 'يسجل الخادم الانسحاب وقد يسوي الرهان كخسارة.',
  'Dice roll failed': 'فشلت رمية النرد',
  'Move failed': 'فشلت الحركة',
  'Forfeit failed': 'فشل الانسحاب',
  'Waiting for': 'بانتظار',
  'You won': 'لقد فزت',
  'The backend has stored the final result and wallet settlement.': 'حفظ الخادم النتيجة النهائية وتسوية المحفظة.',
  'Roll': 'ارمِ',
  'Token': 'القطعة',
  'Game': 'اللعبة',
  'ACTIVE': 'نشطة',
  'WAITING': 'بانتظار اللاعبين',
  'READY': 'جاهزة',
  'FINISHED': 'منتهية',
  'GREEN': 'الأخضر',
  'YELLOW': 'الأصفر',
  'RED': 'الأحمر',
  'BLUE': 'الأزرق',
  'CASUAL': 'عادية',
  'WAGER': 'رهان',
  'PRIVATE': 'خاصة',
  'Enter your account and password': 'أدخل الحساب وكلمة المرور',
  'Login failed': 'فشل تسجيل الدخول',
  "Don't have an account? ": 'ليس لديك حساب؟ ',
  'Welcome back': 'مرحباً بعودتك',
  'Log in to continue your Ludo journey.': 'سجّل الدخول لمتابعة رحلتك في اللودو.',
  'Phone number or email': 'رقم الهاتف أو البريد الإلكتروني',
  'Enter your account': 'أدخل حسابك',
  'Password': 'كلمة المرور',
  'Enter password': 'أدخل كلمة المرور',
  'Log In': 'تسجيل الدخول',
  'Create Account': 'إنشاء حساب',
  'Player name': 'اسم اللاعب',
  'Visible to other players': 'يظهر للاعبين الآخرين',
  'Email (optional)': 'البريد الإلكتروني (اختياري)',
  'At least 10 characters': '10 أحرف على الأقل',
  'Confirm password': 'تأكيد كلمة المرور',
  'Enter your full name': 'أدخل اسمك الكامل',
  'Player name must contain 3 to 24 English letters, numbers or underscores': 'يجب أن يحتوي اسم اللاعب على 3 إلى 24 حرفاً إنجليزياً أو رقماً أو شرطة سفلية',
  'Enter an email or phone number': 'أدخل بريداً إلكترونياً أو رقم هاتف',
  'Enter a valid email address': 'أدخل بريداً إلكترونياً صالحاً',
  'Enter a valid phone number including country code': 'أدخل رقم هاتف صالحاً مع رمز الدولة',
  'Password must contain at least 10 characters': 'يجب أن تحتوي كلمة المرور على 10 أحرف على الأقل',
  'Passwords do not match': 'كلمتا المرور غير متطابقتين',
  'Registration failed': 'فشل إنشاء الحساب',
  'Forgot Password': 'نسيت كلمة المرور',
  'Password recovery is not connected yet': 'استعادة كلمة المرور غير متصلة بعد',
  'No verification code is generated locally. This feature will be enabled only after connecting a real email or SMS provider.': 'لا يتم إنشاء رمز تحقق محلياً. ستُفعّل الميزة فقط بعد ربط مزود حقيقي للبريد الإلكتروني أو الرسائل النصية.',
  'Verification Code': 'رمز التحقق',
  'Verification is not connected yet': 'التحقق غير متصل بعد',
  'The application does not accept test codes. A real OTP provider must be configured first.': 'لا يقبل التطبيق رموزاً تجريبية. يجب إعداد مزود OTP حقيقي أولاً.',
  'New Password': 'كلمة مرور جديدة',
  'Password reset is not connected yet': 'إعادة تعيين كلمة المرور غير متصلة بعد',
  'This page is disabled until a verified recovery token is issued by the backend.': 'هذه الصفحة معطلة حتى يصدر الخادم رمز استعادة موثوقاً.',
  'No password was changed': 'لم يتم تغيير كلمة المرور',
  'Return to login. Password recovery will be available after the verification provider is connected.': 'ارجع إلى تسجيل الدخول. ستتوفر الاستعادة بعد ربط مزود التحقق.',
  'Get Started': 'ابدأ الآن',
  'English interface': 'واجهة باللغة الإنجليزية',
  'واجهة عربية كاملة من اليمين إلى اليسار': 'واجهة عربية كاملة من اليمين إلى اليسار',
  'You can change the language later from settings.': 'يمكنك تغيير اللغة لاحقاً من الإعدادات.',
  'Play classic Ludo': 'العب لودو الكلاسيكية',
  'Challenge players in 2-player and 4-player matches with clear competitive rules.': 'تحدَّ اللاعبين في مباريات ثنائية ورباعية بقواعد تنافسية واضحة.',
  'Tournaments and prizes': 'البطولات والجوائز',
  'Join scheduled tournaments, follow the bracket and compete for the top positions.': 'انضم إلى البطولات المجدولة وتابع الجدول ونافس على المراكز الأولى.',
  'Social rooms': 'الغرف الاجتماعية',
  'Create voice rooms, invite friends, send gifts and build your community.': 'أنشئ غرفاً صوتية وادعُ الأصدقاء وأرسل الهدايا وابنِ مجتمعك.',
  'About': 'حول التطبيق',
  'Enter room code': 'أدخل رمز الغرفة',
  'Match created': 'تم إنشاء المباراة',
  'Players': 'اللاعبون',
  'Privacy': 'الخصوصية',
  'Quick Settings': 'الإعدادات السريعة',
  'Room': 'الغرفة',
  'Support': 'الدعم',
  'Terms & Policies': 'الشروط والسياسات',
  'The connected flow now opens the real waiting room directly.': 'يفتح المسار المتصل الآن غرفة الانتظار الحقيقية مباشرة.',
  'There are no real wallet transactions for this account yet.': 'لا توجد معاملات محفظة حقيقية لهذا الحساب حتى الآن.',
  'This module is not connected yet.': 'هذه الوحدة غير متصلة بعد.',
  'Cancel room?': 'إلغاء الغرفة؟',
  'Leave room?': 'مغادرة الغرفة؟',
  'Cancelling the room returns every reserved wager before the match starts.': 'يؤدي إلغاء الغرفة إلى إعادة جميع الرهانات المحجوزة قبل بدء المباراة.',
  'Leaving before the match starts returns your reserved wager.': 'تؤدي المغادرة قبل بدء المباراة إلى إعادة رهانك المحجوز.',
  'Continue waiting': 'متابعة الانتظار',
  'Cancel room': 'إلغاء الغرفة',
  'Leave room': 'مغادرة الغرفة',
  'Could not leave the room': 'تعذرت مغادرة الغرفة',
  'Room cancelled and wager refunded': 'تم إلغاء الغرفة وإعادة الرهان',
  'Room cancelled': 'تم إلغاء الغرفة',
  'Select a legal token': 'اختر قطعة مسموحاً بتحريكها',
  'Entry amount': 'قيمة الدخول',
  'Status': 'الحالة',
  'Estimated platform fee': 'عمولة المنصة المتوقعة',
  'Estimated winner prize': 'جائزة الفائز المتوقعة',
  'You won the match': 'فزت بالمباراة',
  'Player left the waiting room': 'غادر لاعب غرفة الانتظار',
  'Transaction approved': 'تمت الموافقة على المعاملة',
  'Transaction rejected': 'تم رفض المعاملة',
  'Boards': 'الرقع',
  'Dice': 'النرد',
  'Frames': 'إطارات النرد',
  'Backgrounds': 'الخلفيات',
  'Avatar frames': 'إطارات الصور الشخصية',
  'Emotes': 'الرموز التعبيرية',
  'No items in this category': 'لا توجد عناصر في هذا القسم',
  'The administrator can add products and visual options from the control panel.': 'يمكن للإدارة إضافة المنتجات والخيارات البصرية من لوحة التحكم.',
  'Equip': 'استخدام',
  'Get': 'احصل عليه',
  'EQUIPPED': 'مستخدم حالياً',
  'COMMON': 'عادي',
  'RARE': 'نادر',
  'EPIC': 'ملحمي',
  'LEGENDARY': 'أسطوري',
  'LIMITED': 'محدود',
  'Purchase completed': 'اكتملت عملية الشراء',
  'The item is now available in your inventory.': 'أصبح العنصر متاحاً الآن في حقيبتك.',
  'Stage': 'المرحلة',
  'pieces': 'قطع',
  'Move': 'حرّك',
  'Online payment': 'دفع إلكتروني',
  'Open secure checkout': 'فتح صفحة الدفع الآمنة',
  'Payment request created': 'تم إنشاء طلب الدفع',
  'Could not open payment page': 'تعذر فتح صفحة الدفع',
  'Payment request failed': 'فشل إنشاء طلب الدفع',
  'Request failed': 'فشل الطلب',
  'Choose an active payment method configured by administration. Manual transfers require receipt approval; online methods use the provider checkout.': 'اختر طريقة دفع فعالة أعدّتها الإدارة. التحويل اليدوي يحتاج مراجعة الإيصال، والدفع الإلكتروني يفتح صفحة مزود الدفع.',
  'Optional for online payment': 'اختياري للدفع الإلكتروني',
  'No payment methods are active': 'لا توجد طرق دفع مفعلة',
  'Activate a deposit method from the administration panel.': 'فعّل طريقة إيداع من لوحة التحكم.',
  'No withdrawal method is active': 'لا توجد طريقة سحب مفعلة',
  'Enable a withdrawal method from the administration panel.': 'فعّل طريقة سحب من لوحة التحكم.',
  'Store & visual items': 'المتجر والعناصر البصرية',
  'Seasonal campaign': 'حملة موسمية',
  'Featured': 'مميز',
  'Minimum level': 'الحد الأدنى للمستوى',
  'Default/free': 'افتراضي ومجاني',
  'Level reward': 'مكافأة المستوى',
  'Stage reward': 'مكافأة المرحلة',

  "Offline Play": "اللعب بدون إنترنت",
  "Play without internet": "العب بدون إنترنت",
  "Practice locally against computer players. Offline matches never use or change your wallet.": "تدرّب محلياً ضد لاعبي الكمبيوتر. المباريات دون إنترنت لا تستخدم المحفظة ولا تغيّرها.",
  "Solo vs Computer": "فردي ضد الكمبيوتر",
  "You against one computer player • Classic rules": "أنت ضد لاعب كمبيوتر واحد • القواعد الكلاسيكية",
  "Four-player Practice": "تدريب لأربعة لاعبين",
  "You against three computer players • No server required": "أنت ضد ثلاثة لاعبي كمبيوتر • لا يحتاج خادماً",
  "Offline results are for practice only. They do not affect cash balance, wagers, XP, levels, stages or online statistics.": "نتائج اللعب دون إنترنت للتدريب فقط، ولا تؤثر في الرصيد النقدي أو الرهانات أو الخبرة أو المستويات أو المراحل أو الإحصائيات المتصلة.",
  "Play Offline": "العب بدون إنترنت",
  "Offline / Solo Play": "لعب بدون إنترنت / فردي",
  "Play locally against computer players with no internet and no wager": "العب محلياً ضد الكمبيوتر دون إنترنت ودون رهان",
  "Offline Practice": "تدريب دون إنترنت",
  "No internet • No wager • Classic local rules": "دون إنترنت • دون رهان • قواعد محلية كلاسيكية",
  "Your turn — roll the dice": "دورك — ارمِ النرد",
  "Choose a highlighted piece": "اختر قطعة مضيئة",
  "Computer's turn": "دور الكمبيوتر",
  "Tap the dice": "اضغط على النرد",
  "Computer is thinking...": "الكمبيوتر يفكر...",
  "Tap a highlighted piece on the board": "اضغط على قطعة مضيئة على الرقعة",
  "Practice victory!": "فوز في التدريب!",
  "Practice completed": "انتهى التدريب",
  "You won the offline match. No wallet or online statistics were changed.": "فزت بالمباراة دون إنترنت. لم يتغير رصيد المحفظة أو الإحصائيات المتصلة.",
  "The computer won this practice match. Try again whenever you want.": "فاز الكمبيوتر في هذه المباراة التدريبية. يمكنك المحاولة مجدداً في أي وقت.",
  "Play again": "العب مجدداً",
  "Done": "تم",
  "home": "في المنزل",
  "Online services connected": "الخدمات المتصلة تعمل",
  "Wallet, matches, store and progression are synchronized with the server. Pull down to refresh.": "المحفظة والمباريات والمتجر والتقدم متزامنة مع الخادم. اسحب للأسفل للتحديث.",
  "Play": "العب",
  "Choose casual, cash wager, private room or offline practice.": "اختر مباراة عادية أو رهاناً نقدياً أو غرفة خاصة أو تدريباً دون إنترنت.",
  "Wager Match": "مباراة رهان",
  "Choose stake • Winner takes prize": "اختر قيمة الرهان • الفائز يحصل على الجائزة",
  "Online • No cash wager": "متصلة • دون رهان نقدي",
  "Cash wagering": "الرهان النقدي",
  "Select 2 or 4 players, choose the rules, then choose your stake. The server locks each player stake before the match and settles the prize after the verified result.": "اختر لاعبين أو أربعة، ثم القواعد، ثم قيمة الرهان. يحجز الخادم رهان كل لاعب قبل المباراة ويسوّي الجائزة بعد النتيجة الموثقة.",
  "No matches yet": "لا توجد مباريات بعد",
  "Start a casual or wager match, or use offline practice while you wait for other players.": "ابدأ مباراة عادية أو مباراة رهان، أو استخدم التدريب دون إنترنت أثناء انتظار لاعبين آخرين.",
  "No rooms yet": "لا توجد غرف بعد",
  "Create the first text or voice room.": "أنشئ أول غرفة نصية أو صوتية.",
  "Room name": "اسم الغرفة",
  "Text room": "غرفة نصية",
  "Voice room": "غرفة صوتية",
  "members": "أعضاء",
  "Maximum participants": "الحد الأقصى للمشاركين",
  "Create room": "إنشاء غرفة",
  "Could not create room": "تعذر إنشاء الغرفة",
  "Write a message...": "اكتب رسالة...",
  "No messages yet": "لا توجد رسائل بعد",
  "Say hello to the room.": "ابدأ المحادثة في الغرفة.",
  "Voice provider is not configured yet": "مزود الصوت غير مهيأ بعد",
  "Voice session ready": "جلسة الصوت جاهزة",
  "The voice provider returned a session successfully. Native media transport can now use the returned provider token.": "أعاد مزود الصوت جلسة بنجاح. يمكن الآن لطبقة الصوت الأصلية استخدام رمز المزود.",
  "Voice room: chat is live now. Audio starts when VOICE_TOKEN_ENDPOINT and VOICE_API_KEY are configured on the backend.": "محادثة الغرفة الصوتية تعمل الآن. يبدأ الصوت عند ضبط VOICE_TOKEN_ENDPOINT و VOICE_API_KEY في الخادم.",
  "OK": "موافق",
  "OFFLINE": "دون إنترنت",
  'This build uses real authentication, profile, wallet, payments, store, inventory, appearance, levels, stages, transactions, authoritative online matches, cash-wager reservation/settlement, offline practice and server-backed text/voice room structure. Live voice audio still requires the selected voice provider API. Tournaments, referrals, achievements, support and password recovery remain separate modules.': 'تستخدم هذه النسخة تسجيل الدخول الحقيقي والملف الشخصي والمحفظة والدفع والمتجر والحقيبة والمظهر والمستويات والمراحل والمعاملات والمباريات المتصلة المعتمدة على الخادم وحجز وتسوية الرهانات النقدية والتدريب دون إنترنت وبنية غرف نصية وصوتية مرتبطة بالخادم. يبقى الصوت المباشر بحاجة إلى API مزود الصوت المختار. البطولات والدعوات والإنجازات والدعم واستعادة كلمة المرور وحدات منفصلة متبقية.',
};

const Map<String, String> _arReplacements = {
  'Player\'s turn! Roll the dice.': 'دور اللاعب! ارمِ النرد.',
  "Player's turn": 'دور اللاعب',
  "Bot's turn": 'دور الكمبيوتر',
  'turn! Roll the dice.': 'الدور! ارمِ النرد.',
  'Finding ': 'جاري البحث عن ',
  ' players': ' لاعبين',
  'Prize': 'الجائزة',
  'Casual Match': 'مباراة عادية',
  'Entry amount': 'قيمة الدخول',
  'wins': 'فوز',
  'pts': 'نقطة',
  'online': 'متصل',
  'sent': 'تم الإرسال',
  'Players (': 'اللاعبون (',
  'Victory vs': 'فوز على',
  'vs': 'ضد',
  'days': 'أيام',
  'hours': 'ساعات',
};
