'use client';
import { useEffect,useState } from 'react';import { Shell } from '@/components/shell';import { api, assetUrl, uploadFile } from '@/lib/api';
const empty:any={code:'',surface:'APP_BACKGROUND',nameAr:'',nameEn:'',imageUrl:'',backgroundColor:'#0D0618',textColor:'#FFFFFF',actionType:'',actionValue:'',startsAt:'',endsAt:'',enabled:true,priority:0,metadata:{}};
export default function Appearance(){const[items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState('');const load=()=>api<any[]>('/admin/campaigns').then(setItems);useEffect(()=>{void load()},[]);const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));async function upload(file?:File){if(!file)return;try{const result=await uploadFile('/admin/uploads/assets',file);set('imageUrl',result.url)}catch(e:any){setError(e.message)}}
async function save(e:React.FormEvent){e.preventDefault();try{const body={...form,priority:Number(form.priority),startsAt:form.startsAt?new Date(form.startsAt).toISOString():undefined,endsAt:form.endsAt?new Date(form.endsAt).toISOString():undefined};await api(editing?`/admin/campaigns/${editing}`:'/admin/campaigns',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setForm(empty);setEditing(null);await load()}catch(e:any){setError(e.message)}}
function edit(x:any){setEditing(x.id);setForm({...x,startsAt:x.startsAt?.slice(0,16)||'',endsAt:x.endsAt?.slice(0,16)||''})}
return <Shell><h1>Appearance & seasonal campaigns</h1><p className="muted">Change the whole app background, home/store banners or the game lobby for holidays, offers and events.</p>{error&&<p className="error">{error}</p>}
<form className="card form-grid" onSubmit={save}>
<label>Code<input className="input" value={form.code} disabled={editing!==null} onChange={e=>set('code',e.target.value.toUpperCase())} required/></label>
<label>Surface<select className="input" value={form.surface} onChange={e=>set('surface',e.target.value)}>{['APP_BACKGROUND','HOME_BANNER','STORE_BANNER','GAME_LOBBY'].map(x=><option key={x}>{x}</option>)}</select></label>
<label>Arabic name<input className="input" value={form.nameAr} onChange={e=>set('nameAr',e.target.value)} required/></label>
<label>English name<input className="input" value={form.nameEn} onChange={e=>set('nameEn',e.target.value)} required/></label>
<label>Image / event artwork<input className="input" value={form.imageUrl||''} onChange={e=>set('imageUrl',e.target.value)}/><input className="input" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label>
<label>Background color<input className="input" type="color" value={form.backgroundColor||'#0D0618'} onChange={e=>set('backgroundColor',e.target.value)}/></label>
<label>Text color<input className="input" type="color" value={form.textColor||'#FFFFFF'} onChange={e=>set('textColor',e.target.value)}/></label>
<label>Action<select className="input" value={form.actionType||''} onChange={e=>set('actionType',e.target.value)}><option value="">No action</option>{['STORE','WALLET','PROFILE','PRIVATE_ROOM','RULES','ROUTE'].map(x=><option key={x}>{x}</option>)}</select></label>
<label>Action value<input className="input" value={form.actionValue||''} onChange={e=>set('actionValue',e.target.value)} placeholder="Optional route or game mode"/></label>
<label>Starts at<input className="input" type="datetime-local" value={form.startsAt||''} onChange={e=>set('startsAt',e.target.value)}/></label>
<label>Ends at<input className="input" type="datetime-local" value={form.endsAt||''} onChange={e=>set('endsAt',e.target.value)}/></label>
<label>Priority<input className="input" type="number" value={form.priority} onChange={e=>set('priority',e.target.value)}/></label>
<label className="check"><input type="checkbox" checked={!!form.enabled} onChange={e=>set('enabled',e.target.checked)}/> Enabled</label>
<div className="full preview" style={{background:form.imageUrl?`url(${assetUrl(form.imageUrl)}) center/cover`:form.backgroundColor,color:form.textColor}}><b>{form.nameEn||'Live preview'}</b><span>{form.nameAr}</span></div>
<div className="row full"><button className="btn">{editing?'Save campaign':'Create campaign'}</button>{editing&&<button type="button" className="btn secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>
<div className="grid">{items.map(x=><div className="card" key={x.id}><div className="campaign-cover" style={{background:x.imageUrl?`url(${assetUrl(x.imageUrl)}) center/cover`:x.backgroundColor}}/><h3>{x.nameEn}</h3><p>{x.nameAr}</p><p className="muted">{x.surface} · priority {x.priority}</p><div className="row"><button className="btn secondary" onClick={()=>edit(x)}>Edit</button><button className="btn danger" onClick={async()=>{if(confirm('Delete campaign?')){await api(`/admin/campaigns/${x.id}`,{method:'DELETE'});load()}}}>Delete</button></div></div>)}</div></Shell>}
