'use client';
import { useEffect, useState } from 'react';
import { Shell } from '@/components/shell';
import { api } from '@/lib/api';

const empty:any={code:'',nameAr:'',nameEn:'',descriptionAr:'',descriptionEn:'',ruleCode:'CLASSIC',matchPlayers:2,minPlayers:2,maxPlayers:16,entryFee:0,currency:'MRU',registrationOpensAt:'',registrationClosesAt:'',startsAt:'',sortOrder:0};
export default function Tournaments(){
 const[items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(empty);const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState('');
 const load=()=>api<any[]>('/admin/tournaments').then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();setError('');try{const body={...form,matchPlayers:Number(form.matchPlayers),minPlayers:Number(form.minPlayers),maxPlayers:Number(form.maxPlayers),entryFee:Number(form.entryFee),sortOrder:Number(form.sortOrder),registrationOpensAt:form.registrationOpensAt||undefined,registrationClosesAt:form.registrationClosesAt||undefined,startsAt:form.startsAt||undefined};await api(editing?`/admin/tournaments/${editing}`:'/admin/tournaments',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setEditing(null);setForm(empty);await load()}catch(e:any){setError(e.message)}}
 function edit(x:any){setEditing(x.id);setForm({...x,entryFee:Number(x.entryFee),registrationOpensAt:x.registrationOpensAt?.slice(0,16)||'',registrationClosesAt:x.registrationClosesAt?.slice(0,16)||'',startsAt:x.startsAt?.slice(0,16)||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function action(id:string,name:'open'|'start'|'cancel'){if(name==='start'&&!confirm('Start this tournament and generate the bracket?'))return;if(name==='cancel'&&!confirm('Cancel tournament and refund reserved entry fees?'))return;try{await api(`/admin/tournaments/${id}/${name}`,{method:'POST'});await load()}catch(e:any){setError(e.message)}}
 return <Shell><div className="top"><div><h1>Tournaments</h1><p className="muted">Create registration windows, entry fees and server-generated head-to-head brackets.</p></div></div>{error&&<p className="error">{error}</p>}
 <form className="card form-grid" onSubmit={save}><h2 className="full">{editing?'Edit tournament':'Create tournament'}</h2>
 <label>Code<input className="input" value={form.code} disabled={!!editing} onChange={e=>set('code',e.target.value.toUpperCase())} required/></label><label>Rule code<input className="input" value={form.ruleCode} onChange={e=>set('ruleCode',e.target.value.toUpperCase())}/></label>
 <label>Arabic name<input className="input" value={form.nameAr} onChange={e=>set('nameAr',e.target.value)} required/></label><label>English name<input className="input" value={form.nameEn} onChange={e=>set('nameEn',e.target.value)} required/></label>
 <label>Arabic description<textarea className="input textarea" value={form.descriptionAr||''} onChange={e=>set('descriptionAr',e.target.value)}/></label><label>English description<textarea className="input textarea" value={form.descriptionEn||''} onChange={e=>set('descriptionEn',e.target.value)}/></label>
 <label>Minimum players<input className="input" type="number" min="2" max="128" value={form.minPlayers} onChange={e=>set('minPlayers',e.target.value)}/></label><label>Maximum players<input className="input" type="number" min="2" max="128" value={form.maxPlayers} onChange={e=>set('maxPlayers',e.target.value)}/></label>
 <label>Entry fee<input className="input" type="number" min="0" step="1" value={form.entryFee} onChange={e=>set('entryFee',e.target.value)}/></label><label>Currency<input className="input" value={form.currency} onChange={e=>set('currency',e.target.value.toUpperCase())}/></label>
 <label>Registration opens<input className="input" type="datetime-local" value={form.registrationOpensAt} onChange={e=>set('registrationOpensAt',e.target.value)}/></label><label>Registration closes<input className="input" type="datetime-local" value={form.registrationClosesAt} onChange={e=>set('registrationClosesAt',e.target.value)}/></label>
 <label>Starts at<input className="input" type="datetime-local" value={form.startsAt} onChange={e=>set('startsAt',e.target.value)}/></label><label>Sort order<input className="input" type="number" value={form.sortOrder} onChange={e=>set('sortOrder',e.target.value)}/></label>
 <div className="row full"><button className="btn" type="submit">{editing?'Save changes':'Create'}</button>{editing&&<button className="btn secondary" type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>
 <div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Status</th><th>Entry</th><th>Players</th><th>Starts</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.nameEn}<small>{x.nameAr}</small></td><td><span className="badge">{x.status}</span></td><td>{Number(x.entryFee)} {x.currency}</td><td>{x.minPlayers}–{x.maxPlayers}</td><td>{x.startsAt?new Date(x.startsAt).toLocaleString():'—'}</td><td><div className="row"><button className="btn secondary" onClick={()=>edit(x)}>Edit</button>{x.status==='DRAFT'&&<button className="btn" onClick={()=>action(x.id,'open')}>Open</button>}{['DRAFT','OPEN'].includes(x.status)&&<button className="btn" onClick={()=>action(x.id,'start')}>Start</button>}{x.status!=='COMPLETED'&&x.status!=='CANCELLED'&&<button className="btn danger" onClick={()=>action(x.id,'cancel')}>Cancel</button>}</div></td></tr>)}</tbody></table></div></Shell>
}
